ARG build_image
ARG base_image

FROM $build_image AS build-image

FROM python:3.11 as base

COPY ../dist/*.whl .

RUN pip install *.whl

# Stage 2
FROM $base_image

RUN mkdir /opt/pebblo /opt/pebblo/log /opt/pebblo/config 

WORKDIR /opt/pebblo

COPY --from=base /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages

COPY --from=base /usr/local/bin/pebblo /usr/local/bin/pebblo

ENTRYPOINT ["pebblo"]
